version: CommonIssuesJson-1.{build}
image: Visual Studio 2017
clone_folder: C:\Projects\CommonIssuesJSON
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet build
artifacts:
- path: '**\*.nupkg'
  name: CommonIssuesJSON
deploy:
- provider: NuGet
  api_key:
    secure: 9OYhZ0NK9boRNELSUtp986tMKHUYPoG+LGPCcS6MWNZcAxmgJeUfSfqpiXUI6BVh
  artifact: CommonIssuesJSON